name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Check version changes
      uses: EndBug/version-check@v1.0.0
      id: check
    - name: Version update detected
      if: steps.check.outputs.changed == 'true'
      run: 'echo "Version change! -> ${{ steps.check.outputs.type }}"'
    - name: Install Node
      if: steps.check.outputs.changed == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: 22.17.1
        registry-url: 'https://registry.npmjs.org'
    - name: Install modules
      if: steps.check.outputs.changed == 'true'
      run: npm i
    - name: Build types for tsd
      if: steps.check.outputs.changed == 'true'
      run: npm run build
    - name: Run tests lint, tsd, jest
      if: steps.check.outputs.changed == 'true'
      run: npm run test
    - name: Publish the package to NPM
      if: steps.check.outputs.changed == 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}